### ISSUE TITLE
/restart command does not open the Java minecraft server window (Windows 11)

### ISSUE THREAD

**Issue by FASTB1mc** [Boombabob/Fabric-Server-Essentials#1]
When you do /restart it will shut down the server and immediately start it up again, but when is starts up again it opens the Windows terminal, which is normal, but at a certain point it will open another window called "Minecraft Server". This does not happen when you use /restart instead it just finishes the server-starting in the windows terminal. And because it is in the windows terminal we cannot see how much memory a server is using. 

Thanks

**Comment by james-reynolds1** [comment]
The fix should just be to remove "nogui" from the end of restartArgument in the se_config file in the config folder, unless I am understanding the issue wrong. The reason this is included by default is that it is more performant and generally preferred, but of course you can make it do whatever you want it to.

Please let me know if that fixes the issue!

**Comment by FASTB1mc** [comment]
That fixed it. Thank you.
